=head1 COPYRIGHT AND LICENSE

Copyright (c) 2002, Gary Puckering. All rights reserved. 
 
This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself.  See:

L<http://www.gnu.org/copyleft/gpl.html>

L<http://www.perl.com/language/misc/Artistic.html>

=cut